const data = [
    {
        id: 12174652168498,
        fullName: 'Abhishek Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 1,
        fullName: 'Jay Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 2,
        fullName: 'Anjan Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 3,
        fullName: 'Pawan Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 4,
        fullName: 'Bibek Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 5,
        fullName: 'Ravi Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 6,
        fullName: 'Roshan Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'New',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 7,
        fullName: 'Ram Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'Dead lead',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 8,
        fullName: 'Shyam Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'Dead lead',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 9,
        fullName: 'Sita Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'Dead lead',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 10,
        fullName: 'Kumar Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'Dead lead',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 11,
        fullName: 'Bhuwan Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 12,
        fullName: 'Arjun Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 13,
        fullName: 'Julie Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 14,
        fullName: 'James Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 15,
        fullName: 'Prashant Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 16,
        fullName: 'Darpan Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 17,
        fullName: 'Sulav Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'In progress',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 18,
        fullName: 'Luna Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'Visa waiting',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
    {
        id: 19,
        fullName: 'Radeep Thapa',
        contact: '984252254',
        email: 'abc@gmail.com',
        status: 'Visa waiting',
        counsellor: 'Hira Neupane',
        source: 'Advertisement',
    },
];


export default data;